-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgRqjojJfT3v1CW3s8
a/ovCkkaeKq+Ph7h19XV+g/KvmmgCgYIKoZIzj0DAQehRANCAAT91WkfB8LDAKLd
OkRJJMmbpjlHbE0VOzl8m9jHHEFQgrVoWWPjSZ5WxD2kF1TLkGjtpIcqL3SMdiOs
WCe+5VIQ
-----END PRIVATE KEY-----